### ISSUE TITLE
Storing the results in the database

### ISSUE THREAD

**Issue by tadepask** [cakcora/Chainoba#35]
@mahyamaftouni @maheshkkumar @cakcora @JasmineRandhawa @mariowr2 
Can you please let us know which function to call to store our graph analytics results. Here are a few examples that are generated by the graph metrics:

CURRENT BALANCE DISTRIBUTION:
![current balance](https://user-images.githubusercontent.com/56170232/69094174-7f075780-0a15-11ea-8e86-8e3afd32558c.png)

CHAINLETS RESULT ANALYSIS:

![1](https://user-images.githubusercontent.com/56170232/69093969-2932af80-0a15-11ea-80f1-deaf3f7a1ed3.png)

ADDRESS DISTRIBUTION:

![address dist](https://user-images.githubusercontent.com/56170232/69094139-71ea6880-0a15-11ea-84a3-d430f43a075d.png)

TRANSACTION SIZE DISTRIBUTION:

![transaction size](https://user-images.githubusercontent.com/56170232/69094181-829ade80-0a15-11ea-91e5-350424b73bcc.png)

We have a few more results that will be provided once completed.
Thank you.

**Comment by maheshkkumar** [comment]
@tadepask  If possible, can you please share some sample data for all the different results as csv files with us, so we know more about your data structure and also it will help us to write APIs accordingly. Thanks.

**Comment by srija-srivast** [comment]
Please find the attached sample csv files as requested.

[results sample csv files.zip](https://github.com/cakcora/Chainoba/files/3866583/results.sample.csv.files.zip)

**Comment by maheshkkumar** [comment]
Hi, 

By the way, is this issue related to #46? Please clarify if you need different tables for storing the results or one common tables for all the results. 

Let us know.

**Comment by srija-srivast** [comment]
Hi @maheshkkumar ,

This issue is not related to #46 . 
Yes, we need different tables for storing the results of our analysis. 
Please let us know what details you require from our end regarding the tables for our results.

Thanks

**Comment by maheshkkumar** [comment]
Hi @srija-srivast, 

Also, if possible can you provide more suitable names for each of the column fields in the CSV, we will use the names you provide in the DB tables so as to avoid any confusion later.

Thank you.

**Comment by srija-srivast** [comment]
Hi @maheshkkumar ,

Below are  the columns' name for our different analysis results:

**Address distribution:**
Date
ReceiveOnlyPer
SendReceivePer


**Total BTC received:**
Date
BTCrecLT1
BTCrecLT10
BTCrecLT100
BTCrecLT1000
BTCrecLT10000
BTCrecLT50000
BTCrecGT50000


**Level of activity:**
Date
LOALT2
LOALT5
LOALT10
LOALT100
LOALT1000
LOALT5000
LOAGT5000


**Strongly connected components:**
Date
SCC


**Weakly connected components:**
Date
WCC


**Transaction size:**
Date
TransSizeLT1
TransSizeLT10
TransSizeLT100
TransSizeLT5000
TransSizeLT20000
TransSizeLT50000
TransSizeGT50000


**Assortativity coefficient:**
Date
AssortCoeff


**Bitcoin Circulation:**
Date
TotBTC
CircPercent
NotCircuPercent

**Most active entity:**
Date
Addr
NoOfTrans


**Chainlets Occurance:**
Date
SplitChlt
MergeChlt
TransitionChlt


**Chainlets Occurance Amount:**
Date
SplitChAmt
MergeChAmt
TransitionChAmt


**Clustering coefficient:**
Date
ClustCoeff


**Pearson coefficient:**
Date
PearCoeff


**Current Balance:**
Date
CurrBal1
CurrBal10
CurrBal100
CurrBal1000
CurrBal10000
CurrBal50000
CurrBalGT50000

**Comment by mahyamaftouni** [comment]
@srija-srivast 
Hi, I have few questions
1) You initially requested to store 4 tables:
- Address Distribution
- Current Balance
- Split Chainlet
- transaction size
Your latest message is not clear for me. Are you asking for 14 different tables? 
If yes can you identify the data types?

2) I assume you need an endpoint to **insert** a row in each of the mentioned tables.  (right?)
You just mentioned storing in this issue. Do you also need an endpoint to retrieve stored data?
If yes, for **gett**ing inserted rows, I am going to provide an endpoint to get a row by Date. Do you need anything else?

**Comment by srija-srivast** [comment]
Hi @mahyamaftouni ,

1. Yes, we need all 14 tables to store our analysis results, since we have 14 different analysis. Please find the columns data types as below:
**Address distribution:**
Date- date
ReceiveOnlyPer- float
SendReceivePer -float

**Total BTC received:**
Date - date
BTCrecLT1 - integer
BTCrecLT10 - integer
BTCrecLT100- integer
BTCrecLT1000- integer
BTCrecLT10000- integer
BTCrecLT50000- integer
BTCrecGT50000- integer

**Level of activity:**
Date - date
LOALT2- integer
LOALT5- integer
LOALT10- integer
LOALT100- integer
LOALT1000- integer
LOALT5000- integer
LOAGT5000- integer

**Strongly connected components:**
Date- date
SCC- integer

**Weakly connected components:**
Date-date
WCC- integer

**Transaction size:**
Date - date
TransSizeLT1 - integer
TransSizeLT10- integer
TransSizeLT100- integer
TransSizeLT5000- integer
TransSizeLT20000- integer
TransSizeLT50000- integer
TransSizeGT50000- integer

**Assortativity coefficient:**
Date-date
AssortCoeff- float

**Bitcoin Circulation:**
Date-date
TotBTC- float
CircPercent- float
NotCircuPercent- float

**Most active entity:**
Date - date
Addr- varchar
NoOfTrans - integer

**Chainlets Occurance:**
Date- date
SplitChlt- integer
MergeChlt- integer
TransitionChlt- integer

**Chainlets Occurance Amount:**
Date- date
SplitChAmt - float
MergeChAmt- float
TransitionChAmt- float

**Clustering coefficient:**
Date -date
ClustCoeff- float

**Pearson coefficient:**
Date- date
PearCoeff- float

**Current Balance:**
Date - date
CurrBal1- integer
CurrBal10- integer
CurrBal100- integer
CurrBal1000- integer
CurrBal10000- integer
CurrBal50000- integer
CurrBalGT50000- integer

2. Yes, we have to insert our analysis result in these tables. Yes, we need an endpoint to retrieve the stored  data.

Thank you.

**Comment by mahyamaftouni** [comment]
@srija-srivast so getting stored data by **date** is okay?

**Comment by srija-srivast** [comment]
Hi @mahyamaftouni ,

Yes, getting stored data by date is okay.
Thank you.

**Comment by mahyamaftouni** [comment]
http://159.203.28.234:5000/bitcoin/
http://159.203.28.234:5000/bitcoin/
http://159.203.28.234:5000/bitcoin/

**Comment by mahyamaftouni** [comment]
The requested APIs are developed and would be deployed once our merge request gets accepted.

(GET/POST) SERVER_URL/bitcoin/address_distribution
(GET/POST) SERVER_URL/bitcoin/total_btc_received
(GET/POST) SERVER_URL/bitcoin/activity_level
(GET/POST) SERVER_URL/bitcoin/strongly_connected_component
(GET/POST) SERVER_URL/bitcoin/weakly_connected_component
(GET/POST) SERVER_URL/bitcoin/transaction_size
(GET/POST) SERVER_URL/bitcoin/current_balance
(GET/POST) SERVER_URL/bitcoin/assortativity_coefficient
(GET/POST) SERVER_URL/bitcoin/pearson_coefficient
(GET/POST) SERVER_URL/bitcoin/clustering_coefficient
(GET/POST) SERVER_URL/bitcoin/bitcoin_circulation
(GET/POST) SERVER_URL/bitcoin/most_active_entity
(GET/POST) SERVER_URL/bitcoin/chainlets_occurance
(GET/POST) SERVER_URL/bitcoin/chainlets_occurance_amount

You can insert new tuples by POST, and retrieve stored data by GET.
GET requests' body should be as follows for all endpoints:
`{
	"Date": "2019-11-13"
}`

Here is a sample POST request for inserting in the clustering coefficient table:
`{
	"Date": "2019-11-13",
    "ClustCoeff":7.7
}`
